/* This file is automatically generated. Do not edit. */
package timetracking;

public final class NullItemID
{
	public static final int NULL_22938 = 22938;
	public static final int NULL_22939 = 22939;
	public static final int NULL_22940 = 22940;
	public static final int NULL_23044 = 23044;
	/* This file is automatically generated. Do not edit. */
}
